# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdminUserBookSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminUserBookSearch(self):
    self.driver.get("http://localhost:5173/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-300").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-200:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-200:nth-child(1)").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-200:nth-child(2)").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".text-1\\.5xl").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(1) > .flex > .flex:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(1) > .flex > .flex:nth-child(1)").send_keys("user")
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(1) > .flex > .font-bold:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-200:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-200:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex:nth-child(2) > .flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex:nth-child(2) > .flex").send_keys("A First Course in Artificial Intelligence")
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(2) > .flex > .font-bold:nth-child(2)").click()
  
